version: '3.8'
services:
  server:
    image: app-chat:server
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
    depends_on:
      - db
      - client
  db:
    image: mongo:4.4
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
  client:
    image: app-chat:client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    restart: unless-stopped
    stdin_open: true
    tty: true
  